### ISSUE TITLE
Komponent - Lenkepanel / Sykepengesøknad + Beslutning fra NAV

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#12]
Kan ta utgangspunkt i #7 med mindre ikon.

Lenkepanel med lite ikon, overskrift, undertekst (uten fade), og innhold. Innhold er enten en eller fler arbeidsgivere med grad og varighet i dager, eller tekst (beslutning). Innhold skal være mindre uthevet.

![Screenshot 2019-12-18 at 12 28 04](https://user-images.githubusercontent.com/57399041/71082723-da9e3f80-2191-11ea-9ffb-0c8d625628d8.png)

**Comment by sebdak** [comment]
Er det noe forskjell på denne og #11 ?

**Comment by jhnav** [comment]
Litt forskjell i innhold, men du kan godt lage én komponent som dekker begge behov om det er fornuftig.

**Comment by sebdak** [comment]
Det er 4 forskjellige cases

1. Sykmeldingperiode
2. Sykmelding
3. Søknad
4. Beslutning fra NAV

Alle har tittel og et underfelt (noen er grå, mens andre ikke. Synes det burde være likt her, så skal snakke med bendik). 2-4 har også en status på bunn. Alle har ikon, men kun nr 1 har annen størrelse.

Forslag:
Lage denne som en base:
<LenkepanelWrapper tittel: string informasjon: string statusmelding: string ikonStor: boolean/>

Deretter lage egne sykmelding, søknad, periode og beslutning wrappere rundt den.

**Comment by jhnav** [comment]
Kan godt lukke de andre issuesene om denne dekker alle behov.
