### ISSUE TITLE
Siden scrolles ikke til toppen ved navigering med react-router

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#38]
Når man navigerer bør man scrolles til toppen av siden man navigerer til.

Se om det finnes en overordnet løsning for dette via react-router.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md

**Comment by jhnav** [comment]
Forsøkt løst med lenket løsning over.

Problem: Hvis man går fra side A til side B, så scrolles vinduet til toppen som forventet.
Hvis man går tilbake fra side B til side A, så scrolles også vinduet til toppen. Den skal scrolles tilbake til posisjonen brukeren var på.

Testet i andre apper som også bruker react-router (feks foreldrepenger-inngang) og de returnerer til forrige posisjon som ventet.

**Comment by sebdak** [comment]
https://www.npmjs.com/package/react-router-scroll-memory
