### ISSUE TITLE
Font og tekststørrelser

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#48]
Font må defineres.

Enkelte komponenter har feil tekststørrelse. Dette gjelder særlig overskrifter som er for små.

I tillegg mangler:
- en "faded" tekstfarge, grået ut
- en måte å sette "bold" tekstfarge

**Comment by sebdak** [comment]
Er de for små i forhold til skissene? Tror vi burde bruke de typografi-komponentene som finnes i nav-frontend-typografi, og heller få bendik til å endre i skisser. 

Hvis det mangler måter å endre typografien på, så kan vi vurdere å ta en PR til designfolka

**Comment by jhnav** [comment]
Ja, i forhold til skisser.

Ser nå at vi bruker riktig font i forhold til designbiblioteket.

Undersøker mulighet for faded-tekst og bold-tekst i lenkepanel.

**Comment by jhnav** [comment]
#51 endrer statustekst i sykmeldingpanel til "Element" for fet tekst.
