### ISSUE TITLE
Forbedring - Kategori

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#49]
Kategori-komponenten tar kun i mot ett array.

Under "Nye varsler" på DokumentOversikt skal vi vise både Sykmeldinger og Søknader.

**Comment by sebdak** [comment]
Kan gjøre gjøre det, men da føler jeg den blir mindre generell. Kategori bryr seg ikke om det er en søknad eller sykmelding, den legger bare på "UnderstreketOverskrift" og printer ut jsx element(er).

Hva tenker du om:
```
const sykmeldinger = ...
const soknader = ...

const sykmeldingPaneler = sykmeldinger.map((sm, index) => <SykmeldingPanel....)
const soknadPaneler = soknader.map((sok, index) => <SoknaPanel...)

<Kategori tittel="Tittel">
    [...sykmeldingPaneler, ...soknadPaneler]
</Kategori>
```

**Comment by jhnav** [comment]
Høres enklere ut å gjøre det på den måten
