### ISSUE TITLE
Refaktorering av DataFetcher

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#52]
DataFetcher brukes på "feil" måte. Den henter data som man ikke trenger før senere i løpet.

DataFetcher bør fortsatt brukes til å wrappe komponenter som skal bruke data den henter, men den bør splittes opp i flere DataFetcher-komponenter.

Feks bør DittSykefravaer wrappes i en Fetcher som henter alle sykefravaer.

**Comment by sebdak** [comment]
Enig at vi burde laste ting når det trengs. Blir det for denne appen mer datahenting enn "sykefravaer", hvis et sykefravaer inneholder én eller flere sykmeldinger og søknader? Dersom man går man inn på én bestemt sykmelding vil man sendes til "sykmeldinger"-appen, og den bestemte sykmeldingen vil bli lastet.

**Comment by jhnav** [comment]
Nei, hittil er det kun Sykefravær som skal hentes, så spørs det på datamodellen om arbeidsgiver og slike ting er inkludert i et fravær eller må hentes separat.

Sånn sett kan vi endre denne oppgaven til å være en opprydding. Henting av sykemeldinger er fortsatt i mock/datafetcher/useAppStore og kan fjernes.

**Comment by jhnav** [comment]
Problem: Vi trenger ikke hente alle sykefravær alltid. Feks hvis vi er på en side som har en URL med et sykefraværId i, trenger vi kun å hente ut det ene sykefraværet.

1. Brukeren bekrefter sykmeldingen i sykmeldingappen.
2. Appen mottar oppdatert sykmelding fra backend.
3. Sykmeldingappen redirecter tilbake til et sykefravær. Den redirecter da til en URL som har en sykefraværId.
4. Siden brukeren går tilbake til en URL med sykefraværId, trenger vi ikke å hente alle sykefravær.

Så er spørsmålet om dette er verdt å tenke på. Problemet med å hente alle sykefravær er performance, antagelig kun i backend. Størrelsen på det man henter er nok ikke noen utfordring. Henter vi kun ett sykefravær sparer vi antagelig prosesseringstid i backend.

Tenker vi tar dette på sikt når backenden skal kobles opp.

**Comment by sebdak** [comment]
Enig, vi tar dette på sikt. Kan være greit å hente alle sykefravær hver gang man redirectes tilbake. Ellers kan vi ikke ha en Datafetcher som wrapper hele appen.
