### ISSUE TITLE
Komponent - Lenkepanel / Standard

### ISSUE THREAD

**Issue by jhnav** [navikt/nytt-sykefravaer#7]
Lenkepanel med ikon til venstre og overskrift/undertekst.

Må oppføre seg som knapp med shadow og cursor-endring ved mouseover. Endrer også fargen på tekst for å indikere knapp.

Se LenkepanelBase i designsystemet.

![Screenshot 2019-12-18 at 12 24 57](https://user-images.githubusercontent.com/57399041/71082454-68c5f600-2191-11ea-91c9-4c70925c643b.png)

**Comment by sebdak** [comment]
Påbegynt, må forbedres

**Comment by jhnav** [comment]
SVGen har ikke noen bakgrunnsfarge, så denne må også kunne settes.

Foreslår fargetema-string: "info", "advarsel", etc tilsvarende fargetema-mulighetene til komponenter i designsystemet. Se https://design.nav.no/components/alertstripe for eksempel.

**Comment by sebdak** [comment]
Har pratet med bendik, og ikonet skal ikke være større på dette panelet enn de andre. Bruker derfor samme komponent til alle tilfeller

**Comment by jhnav** [comment]
Ser at i Foreldrepenger så skjules ikonet ved små skjermbredder.

**Comment by sebdak** [comment]
testet nettopp uten ikon for små skjermbredder. synes ikonet bidrar til å differensiere mellom de forskjellige paneltypene, og at det kanskje er greit å beholde for brukervennlighetens skyld. Kan høre med bendik hva han tenker
